### ISSUE TITLE
Violation of PSR-0 standard

### ISSUE THREAD

**Issue by SOF3** [Awzaw/LockIt#1]
Your namespace is `LockIt` but your folder is `lockit`. This may result in problems loading the plugin in case-sensitive filesystems.

You have so far not encountered such problem because you use `lockit` as the namespace in the `plugin.yml`. But this issue might still lead to crashes in the future.

See: http://poggit.mcpe.me/poggit/build/SOF3/LockIt/LockIt/dev:1#lints

**Comment by Awzaw** [comment]
thanks!
